algorithm: freematch
save_dir: /root/autodl-tmp/savemodel
save_name: freematch_cifar10
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 102400
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 200
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0.001
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.000001
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: eva_large_patch14_196_in22k_ft_in22k_in1k
net_from_name: False
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
seed: 0
world_size: 1
rank: 0
noisy_file: nosiy_labels_CIFAR10_cifar10_e1